### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by chelsplanner** [ivyngu/book-scraper#1]
Hi, 

Can you write out the instructions on how to put the API key in a .env file? Is it possible to pull out other book details like ISBN, genre, ratings, year published, publisher etc?

**Comment by ivy-phngyn** [comment]
Hi,

Yes, I will add these instructions, sorry for not making it clear in the
first place. At the moment I haven't added any features for pulling out any
other book details, but I can definitely add them—thank you very much for
the suggestion! I will work on this promptly.

Have a great day!
